export const GET_ACCOUNT_IMAGE = "GET_ACCOUNT_IMAGE";
export const CLEAR_ACCOUNT_IMAGE = "CLEAR_ACCOUNT_IMAGE";
export const GET_ACCOUNT_IMAGE_FAILS = "GET_ACCOUNT_IMAGE_FAILS";
export const START_FETCH_ACCOUNT_IMAGE = "START_FETCH_ACCOUNT_IMAGE";
